FROM node@sha256:27fab5920246070cf13449cf44c25bc4f5adef18ca7482b2bda90b7cf9e64481
WORKDIR /app
RUN npm i -g ts-node-dev
ADD ./ffmpeg.tar.xz /opt
RUN mv /opt/ffmpeg-git-20220910-amd64-static /opt/ffmpeg
ADD  ./potree.tar.gz /opt
ADD ./public.tar /app
RUN mv /opt/build /opt/potree
RUN cp /opt/potree/liblaszip.so /usr/lib
COPY package*.json ./
RUN npm ci
COPY ./tsconfig.json ./
ENV NODE_ENV=development
CMD ["ts-node-dev", "src/server.ts"]

