services:
  server:
    build:
      context: .
      dockerfile: dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./aru-common:/app/aru-common
      - ./public:/app/public:rw
      - ./adapter:/app/adapter:ro
    environment:
      - TZ="Asia/Kolkata"
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/test
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET_NAME=aru
      - S3_ENDPOINT=minio
      - RABBITMQ_CONNECTION_STRING=amqp://rabbitmq
    env_file:
      - ./server.env
    depends_on:
      mongodb:
        condition: service_healthy
      minio:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - 5011:5011
    extra_hosts:
      - host.docker.internal:host-gateway
    mem_limit: 2g
    memswap_limit: 4g
    cpus: 1.5

  mongodb:
    image: mongo@sha256:06cd2e814b2641d4c7ac6b093e870fe72c1ddbc7c6ddaaef16d4cb5a61c0ee6b
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_DATABASE=test
    ports:
      - 27017:27017
    mem_limit: 256m
    memswap_limit: 512m
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 20s
      retries: 3

  titiler:
    environment:
      - PORT=8000
      - WORKERS_PER_CORE=1
      - MAX_WORKERS=1
    image: ghcr.io/developmentseed/titiler@sha256:86d3caa383c6a44752f662f40701b163727226318ba4f3f370f0fe8f660ec69e
    ports:
      - 8000:8000
    mem_limit: 256m
    memswap_limit: 256m
    cpus: 0.5
    networks:
      - aru

  minio:
    image: minio/minio@sha256:c7175077d39a8cc10c9fd611cdcc68b6a5b365793e9ac6f4198ffff1ef0fe555
    command: server /data --console-address ":9001" --address ":80"
    expose:
      - "9000"
      - "9001"
    healthcheck:
      test: ["CMD", "curl", "-I", "http://localhost:80/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - 9001:9001
      - 9000:80
    networks:
      - aru

  createbuckets:
    image: minio/mc
    volumes:
      - ./assets:/assets
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
        /usr/bin/mc alias set myminio http://minio:80 minioadmin minioadmin;
        /usr/bin/mc mb myminio/aru;
        /usr/bin/mc anonymous set public myminio/aru;
        /usr/bin/mc ilm rule add myminio/aru/temp --expire-days "1"
        /usr/bin/mc cp /assets/*.geojson myminio/aru/vector/
        /usr/bin/mc cp /assets/*.tif myminio/aru/raster/
        /usr/bin/mc cp /assets/layerFileImages/*.png myminio/aru/images/geojson/
        exit 0;
      "
    networks:
      - aru

  vod:
    image: vod:1.0.0
    profiles:
      - vod
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - S3_BUCKET=aru
      - S3_ENDPOINT=http://minio
      - S3_PATH_STYLE=true
      - AMQP_ADDR=amqp://rabbitmq:5672/%2f
      - RUST_LOG=debug

  zip:
    image: zip:latest
    profiles:
      - zip
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - S3_BUCKET=aru
      - S3_ENDPOINT=http://minio
      - S3_PATH_STYLE=true
      - AMQP_ADDR=amqp://rabbitmq:5672/%2f
      - RUST_LOG=debug

  rabbitmq:
    image: rabbitmq@sha256:473953b02b8346091f0b3a6819e017618cbe95cb568bca2fecf00966a20ccf2a
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "status"]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - 5672:5672
    networks:
      - aru
    # mem_limit: 128m
    # memswap_limit: 128m

networks:
  aru:
    name: aru
    external: false
