services:
  server:
    build:
      context: .
      dockerfile: dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./public:/app/public:rw
    environment:
      - TZ="Asia/Kolkata"
      - MONGODB_CONNECTION_STRING=mongodb://mongodb:27017/test
    env_file:
      - ./server.env
    depends_on:
      - mongodb
    ports:
      - 5011:5011

  mongodb:
    image: mongo@sha256:06cd2e814b2641d4c7ac6b093e870fe72c1ddbc7c6ddaaef16d4cb5a61c0ee6b
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_DATABASE=test
    ports:
      - 27019:27017

  titiler:
    environment:
      - PORT=8000
      - WORKERS_PER_CORE=1
    image: ghcr.io/developmentseed/titiler@sha256:45565498b88d5b77360014ab9dd217c17617ae59d308769f67c24e7540a78d02
    ports:
      - 8000:8000

  redis:
    image: redis@sha256:aeed51f49a6331df0cb2c1039ae3d1d70d882be3f48bde75cd240452a2348e88
