services:
  server:
    environment:
      - REDIS_URI=redis://redis:6379
      # - DEBUG=*
    depends_on:
      - redis
    ports:
      - 5011:5011

  mongodb:
    ports:
      - 27017:27017

  redis:
    image: redis@sha256:aeed51f49a6331df0cb2c1039ae3d1d70d882be3f48bde75cd240452a2348e88
    ports:
      - 6379:6379
