const sampleData = {
  missionHeading: "",
  missionSubHeading: "",
  missionMapImg: "",
  missionCode: "",
  date: "13/09/23",
  users: [],
  emails: ["akash.adhlkary@santa.in", "subhendu.panja@santa.in"],
  phoneNos: [],
  address: "",
  Plot_No: "AA/8",
  Premises_No: "18-0072Pl",
  Plot_Area: 333.62,
  Building_Available: true,
  Pincode: 700163,
  Plot_Category: "",
  No_of_Floor: "",
  Sanctioned_Building_No: "",
  Building_Area: 186.7,
  Building_Footprint: 55.8,
  Completion_Certificate: "",
  Average_Building_Height: 0,
  Infraction: "",
  Eligible_For_Green_Top: true,
  Solar_Plant_Incentives: false,
  Trade_License: "",
  Property_Tax: "",
  Garbage_Collector_Information: "",
  Average_Block_Height: "",
  Averag_Block_Height: "",
  Average_Incentives: "",
  water: 0,
  green: 0,
  Tree_canopy: 0,
};