import mongoose from "mongoose";
import { UserTypes } from "./user";
import UserGroup from "../models/usergroup";

export enum PERMS {
  ADD_FEATURE = "add_feature",
  ALERT_CREATE = "alert_create",
  ALERT_DELETE = "alert_delete",
  ALERT_LIST = "alert_list",
  ALERT_UPDATE = "alert_update",
  ASSET_CLASS_LIST = "asset_class_list",
  ASSET_CREATE = "asset_create",
  ASSET_DELETE = "asset_delete",
  ASSET_LIST = "asset_list",
  ASSET_UPDATE = "asset_update",
  CAN_CREATE_BASE_LAYER = "can_create_base_layer",
  CAN_DELETE_BASE_LAYER = "can_delete_base_layer",
  CAN_EDIT_BASE_LAYER = "can_edit_base_layer",
  CAN_UPDATE_BASE_LAYER = "can_update_base_layer",
  CAN_UPLOAD_TO_BASE_LAYER = "can_upload_to_base_layer",
  CLIENT_DATA = "client_data",
  CLIENT_LIST = "client_list",
  CLIENT_MISSION_LIST = "client_mission_list",
  COMMENT_DELETE = "comment_delete",
  CREATE_CLIENT = "create_client",
  DASHBOARD = "dashboard",
  DATA_PAGE = "data_page",
  DELETE_CLIENT = "delete_client",
  DELETE_DOCUMENT = "delete_document",
  DELETE_FEATURE = "delete_feature",
  DELETE_LAYER = "delete_layer",
  DOWNLOAD_LAYER = "download_layer",
  EDIT_CLIENT = "edit_client",
  EDIT_FEATURE = "edit_feature",
  EDIT_LAYER = "edit_layer",
  FEATURE_FILE_DELETE = "feature_file_delete",
  FEATURE_FILE_UPLOAD = "feature_file_upload",
  FLIGHT_LOG_LIST = "flight_log_list",
  LOCATION_CREATE = "location_create",
  LOCATION_DELETE = "location_delete",
  LOCATION_LIST = "location_list",
  LOCATION_UPDATE = "location_update",
  MANUFACTURER_CREATE = "manufacturer_create",
  MANUFACTURER_DELETE = "manufacturer_delete",
  MANUFACTURER_LIST = "manufacturer_list",
  MANUFACTURER_UPDATE = "manufacturer_update",
  MISSION_CREATE = "mission_create",
  MISSION_DELETE = "mission_delete",
  MISSION_LIST = "mission_list",
  MISSION_UPDATE = "mission_update",
  MODEL_CREATE = "model_create",
  MODEL_DELETE = "model_delete",
  MODEL_LIST = "model_list",
  MODEL_UPDATE = "model_update",
  SAVE_DRAWINGS = "save_drawings",
  SET_COVER_PHOTO = "set_cover_photo",
  THREAD_CREATE = "thread_create",
  THREAD_LIST = "thread_list",
  THREAD_UPDATE = "thread_update",
  UPLOAD_DOCUMENT = "upload_document",
  UPLOAD_LAYER = "upload_layer",
  USER_CREATE = "user_create",
  USER_LIST = "user_list",
  VOD_CREATE = "vod_create",
  VOD_DELETE = "vod_delete",
  VOD_LIST = "vod_list",
  VOD_UPDATE = "vod_update",
  WEBRTC_VIEW = "webrtc_view",
  TENANT_CREATE = "tenant_create",
  TENANT_UPDATE = "tenant_update",
  TENANT_DELETE = "tenant_delete",
  TENANT_LIST = "tenant_list",
  TENANT_UPDATE_SELF = "tenant_update_self",
  TENANT_LIST_SELF = "tenant_list_self",
  PACKAGE_CREATE = "package_create",
  PACKAGE_LIST = "package_create",
  PACKAGE_UPDATE = "package_create",
  PACKAGE_DELETE = "package_create",
  PUBLIC_MAP_CREATE = "public_map_create",
  MISSION_TYPE_CREATE = "mission_type_create",
  MISSION_TYPE_UPDATE = "mission_type_update",
  MISSION_TYPE_DELETE = "mission_type_delete",
  ASSET_CLASS_CREATE = "asset_class_create",
  ASSET_CLASS_UPDATE = "asset_class_update",
  ASSET_CLASS_DELETE = "asset_class_delete",
  OTP_EMAIL_SEND = "otp_email_send",
}

export const TENANT_CLIENT_PERMS = <const>[
  PERMS.ASSET_LIST,
  PERMS.CLIENT_MISSION_LIST,
  PERMS.DASHBOARD,
  PERMS.DOWNLOAD_LAYER,
  PERMS.MISSION_LIST,
  PERMS.MISSION_UPDATE,
  PERMS.SAVE_DRAWINGS,
  PERMS.UPLOAD_DOCUMENT,
  PERMS.VOD_LIST,
];

export const TENANT_STAFF_PERMS = <const>[
  ...TENANT_CLIENT_PERMS,
  PERMS.ADD_FEATURE,
  PERMS.ALERT_CREATE,
  PERMS.ALERT_DELETE,
  PERMS.ALERT_LIST,
  PERMS.ALERT_UPDATE,
  PERMS.ASSET_CLASS_LIST,
  PERMS.ASSET_CREATE,
  PERMS.ASSET_DELETE,
  PERMS.ASSET_LIST,
  PERMS.ASSET_UPDATE,
  PERMS.CAN_CREATE_BASE_LAYER,
  PERMS.CAN_DELETE_BASE_LAYER,
  PERMS.CAN_EDIT_BASE_LAYER,
  PERMS.CAN_UPDATE_BASE_LAYER,
  PERMS.CAN_UPLOAD_TO_BASE_LAYER,
  PERMS.CLIENT_DATA,
  PERMS.CLIENT_LIST,
  PERMS.CLIENT_MISSION_LIST,
  PERMS.CREATE_CLIENT,
  PERMS.DASHBOARD,
  PERMS.DATA_PAGE,
  PERMS.DELETE_CLIENT,
  PERMS.DELETE_DOCUMENT,
  PERMS.DELETE_FEATURE,
  PERMS.DELETE_LAYER,
  PERMS.DOWNLOAD_LAYER,
  PERMS.EDIT_CLIENT,
  PERMS.EDIT_FEATURE,
  PERMS.EDIT_LAYER,
  PERMS.FEATURE_FILE_DELETE,
  PERMS.FEATURE_FILE_UPLOAD,
  PERMS.LOCATION_CREATE,
  PERMS.LOCATION_DELETE,
  PERMS.LOCATION_LIST,
  PERMS.LOCATION_UPDATE,
  PERMS.MANUFACTURER_CREATE,
  PERMS.MANUFACTURER_DELETE,
  PERMS.MANUFACTURER_LIST,
  PERMS.MANUFACTURER_UPDATE,
  PERMS.MISSION_CREATE,
  PERMS.MISSION_DELETE,
  PERMS.MISSION_LIST,
  PERMS.MISSION_UPDATE,
  PERMS.MODEL_CREATE,
  PERMS.MODEL_DELETE,
  PERMS.MODEL_LIST,
  PERMS.MODEL_UPDATE,
  PERMS.SAVE_DRAWINGS,
  PERMS.SET_COVER_PHOTO,
  PERMS.UPLOAD_DOCUMENT,
  PERMS.UPLOAD_LAYER,
  PERMS.USER_CREATE,
  PERMS.USER_LIST,
  PERMS.VOD_CREATE,
  PERMS.VOD_DELETE,
  PERMS.VOD_LIST,
  PERMS.VOD_UPDATE,
];

export const TENANT_ROOT_PERMS = <const>[...TENANT_STAFF_PERMS];
export const SUPER_ADMIN_PERMS = <const>[...TENANT_ROOT_PERMS];

export const GetPermissions = async (userGroupId: mongoose.Types.ObjectId, userType: UserTypes, tenantId: mongoose.Types.ObjectId) => {
  let customPermissions: PERMS[] = [];
  if (userType == "tenant-staff" || userType == "tenant-client") {
    const usergroup = await UserGroup.findOne({ _id: userGroupId, tenantId });
    customPermissions = usergroup.permissions;
  }
  else if (userType == "tenant-root") {
    customPermissions = [...TENANT_ROOT_PERMS]
  }
  else if (userType == "super-admin") {
    customPermissions = [...SUPER_ADMIN_PERMS]
  }

  return customPermissions;
}
