export enum PERMS {
  MISSION_CREATE = "mission_create",
  MISSION_DELETE = "mission_delete",
  DATA_PAGE = "data_page",
  ASSET_LIST = "asset_list",
  LOCATION_UPDATE = "location_update",
  LOCATION_DELETE = "location_delete",
  MANUFACTURER_DELETE = "manufacturer_delete",
  MANUFACTURER_LIST = "manufacturer_list",
  VOD_CREATE = "vod_create",
  VOD_DELETE = "vod_delete",
  ADD_FEATURE = "add_feature",
  UPLOAD_LAYER = "upload_layer",
  DOWNLOAD_LAYER = "download_layer",
  CLIENT_MISSION_LIST = "client_mission_list",
  EDIT_CLIENT = "edit_client",
  CLIENT_DATA = "client_data",
  USER_CREATE = "user_create",
  CAN_UPDATE_BASE_LAYER = "can_update_base_layer",
  CAN_UPLOAD_TO_BASE_LAYER = "can_upload_to_base_layer",
  MISSION_LIST = "mission_list",
  ASSET_CREATE = "asset_create",
  LOCATION_LIST = "location_list",
  MANUFACTURER_CREATE = "manufacturer_create",
  MODEL_DELETE = "model_delete",
  VOD_UPDATE = "vod_update",
  ALERT_DELETE = "alert_delete",
  ALERT_LIST = "alert_list",
  MISSION_UPDATE = "mission_update",
  MODEL_CREATE = "model_create",
  MODEL_UPDATE = "model_update",
  MODEL_LIST = "model_list",
  VOD_LIST = "vod_list",
  ALERT_CREATE = "alert_create",
  ALERT_UPDATE = "alert_update",
  SET_COVER_PHOTO = "set_cover_photo",
  EDIT_LAYER = "edit_layer",
  SAVE_DRAWINGS = "save_drawings",
  UPLOAD_DOCUMENT = "upload_document",
  DELETE_CLIENT = "delete_client",
  CLIENT_LIST = "client_list",
  CAN_EDIT_BASE_LAYER = "can_edit_base_layer",
  ASSET_UPDATE = "asset_update",
  ASSET_DELETE = "asset_delete",
  ASSET_CLASS_LIST = "asset_class_list",
  USER_LIST = "user_list",
  LOCATION_CREATE = "location_create",
  MANUFACTURER_UPDATE = "manufacturer_update",
  DASHBOARD = "dashboard",
  FEATURE_FILE_UPLOAD = "feature_file_upload",
  FEATURE_FILE_DELETE = "feature_file_delete",
  EDIT_FEATURE = "edit_feature",
  DELETE_FEATURE = "delete_feature",
  DELETE_LAYER = "delete_layer",
  DELETE_DOCUMENT = "delete_document",
  CREATE_CLIENT = "create_client",
  CAN_CREATE_BASE_LAYER = "can_create_base_layer",
  CAN_DELETE_BASE_LAYER = "can_delete_base_layer",
  FLIGHT_LOG_LIST = "flight_log_list",
  WEBRTC_VIEW = "webrtc_view",
  THREAD_CREATE = "thread_create",
  THREAD_UPDATE = "thread_update",
  THREAD_LIST = "thread_list",
  COMMENT_DELETE = "comment_delete",
}

export const TENANT_CLIENT_PERMS = <const>[
  PERMS.CLIENT_MISSION_LIST,
  PERMS.UPLOAD_DOCUMENT,
  PERMS.DOWNLOAD_LAYER,
  PERMS.VOD_LIST,
  PERMS.DASHBOARD,
  PERMS.MISSION_UPDATE,
  PERMS.SAVE_DRAWINGS,
  PERMS.ASSET_LIST,
  PERMS.MISSION_LIST,
];

export const TENANT_STAFF_PERMS = <const>[
  ...TENANT_CLIENT_PERMS,
  PERMS.MANUFACTURER_CREATE,
  PERMS.VOD_CREATE,
  PERMS.VOD_DELETE,
  PERMS.EDIT_CLIENT,
  PERMS.LOCATION_CREATE,
  PERMS.ALERT_LIST,
  PERMS.ALERT_DELETE,
  PERMS.EDIT_FEATURE,
  PERMS.ASSET_LIST,
  PERMS.DATA_PAGE,
  PERMS.DASHBOARD,
  PERMS.DOWNLOAD_LAYER,
  PERMS.CAN_CREATE_BASE_LAYER,
  PERMS.LOCATION_LIST,
  PERMS.UPLOAD_LAYER,
  PERMS.MISSION_CREATE,
  PERMS.MISSION_LIST,
  PERMS.MANUFACTURER_UPDATE,
  PERMS.LOCATION_DELETE,
  PERMS.ASSET_UPDATE,
  PERMS.MISSION_DELETE,
  PERMS.CAN_UPLOAD_TO_BASE_LAYER,
  PERMS.MODEL_CREATE,
  PERMS.ALERT_UPDATE,
  PERMS.CLIENT_MISSION_LIST,
  PERMS.SET_COVER_PHOTO,
  PERMS.ASSET_DELETE,
  PERMS.ASSET_CLASS_LIST,
  PERMS.ALERT_CREATE,
  PERMS.MODEL_DELETE,
  PERMS.CAN_DELETE_BASE_LAYER,
  PERMS.CAN_UPDATE_BASE_LAYER,
  PERMS.FEATURE_FILE_DELETE,
  PERMS.EDIT_LAYER,
  PERMS.USER_CREATE,
  PERMS.DELETE_LAYER,
  PERMS.ASSET_CREATE,
  PERMS.FEATURE_FILE_UPLOAD,
  PERMS.DELETE_FEATURE,
  PERMS.ADD_FEATURE,
  PERMS.UPLOAD_DOCUMENT,
  PERMS.MODEL_LIST,
  PERMS.SAVE_DRAWINGS,
  PERMS.CREATE_CLIENT,
  PERMS.DELETE_CLIENT,
  PERMS.VOD_UPDATE,
  PERMS.DELETE_DOCUMENT,
  PERMS.USER_LIST,
  PERMS.CLIENT_DATA,
  PERMS.MANUFACTURER_DELETE,
  PERMS.MODEL_UPDATE,
  PERMS.CLIENT_LIST,
  PERMS.MISSION_UPDATE,
  PERMS.LOCATION_UPDATE,
  PERMS.VOD_LIST,
  PERMS.MANUFACTURER_LIST,
  PERMS.CAN_EDIT_BASE_LAYER,
];

export const TENANT_ROOT_PERMS = <const>[...TENANT_STAFF_PERMS];
export const SUPER_ADMIN_PERMS = <const>[...TENANT_ROOT_PERMS];