export enum featureTypes {
  POINT = "Point",
  MULTI_LINE_STRING = "MultiLineString",
  MULTI_POLYGON = "MultiPolygon",
  AIR_POLLUTION = "air_pollution",
  WIND_DIRECTION = "wind_direction",
  POLYGON = "Polygon",
}

export enum vectorProps {
  ZONE_BOUNDARY = "Zone Boundary",
  BLOCK_BOUNDARY = "Block Boundary",
  AREA_BOUNDARY = "Area Boundary",
  MEDIAN = "Median",
  DRAINAGE_NETWORK = "Drainage Network",
  ELECTRIC_POLE = "Electric Pole",
  GARBAGE_COLLECTION_POINT = "Garbage Collection Point",
  LANDMARK = "Landmark",
  VACANT_PLOT = "Vacant Plot",
  CYCLE_STAND = "Cycle Stand",
  SOLAR_AREA = "Solar Area",
  SUB_STATION = "Sub Station",
  METRO_STATION = "Metro Station",
  PLAYGROUND = "Playground",
  RESTRICTED_AREA = "Restricted Area",
  ELECTION_WARD_BOUNDARY = "Election Ward Boundary",
  LANDFILL = "Landfill",
  FLYOVER = "Flyover",
  CARRIAGE_WAY = "Carriage Way",
  CYCLE_TRACK = "Cycle Track",
  CANAL = "Canal",
  POWER_SUPPLY_NETWORK = "Powersupply Network",
  CELLPHONE_TOWER = "Cellphone Tower",
  MANHOLE = "Manhole",
  BUS_SHELTERS = "Bus Shelters",
  METRO_ROUTE = "Metro Route",
  PARKING_AREA = "Parking Area",
  POTHOLES = "Potholes",
  MUNICIPAL_BOUNDARY = "Municipal Boundary",
  WATER_BODY = "Waterbody",
  GREEN_VERGE = "Green Verge",
  PANCHAYAT_BOUNDARY = "Panchayat Boundary",
  REVENUE_WARD_BOUNDARY = "Revenue Ward Boundary",
  FIRE_STATION = "Fire Station",
  ROUNDABOUT = "Roundabout",
  PLOT = "Plot",
  BOUNDARY_WALL = "Boundary Wall",
  PUMPING_STATION = "Pumping Station",
  OVER_HEAD_TANK = "Over Head Tank",
  SEWERAGE_NETWORK = "Sewerage Network",
  PUBLIC_CONVENIENCE = "Public Convenience",
  BUILDING_FOOTPRINT = "Building Footprint",
  JUNGLE = "Jungle",
  PARK = "Park",
  SLUM_BOUNDARY = "Slum Boundary",
  SECTOR_BOUNDARY = "Sector Boundary",
  RIGHT_OF_WAY = "Right of Way",
  FOOTPATH = "Footpath",
  PARCEL = "Parcel",
  CIRCLE = "Circle",
  WATER_TRANSMISSION_LINE = "Water Transmission Line",
  WATER_TREATMENT_PLANT = "Water Treatment Plant",
  DRAINAGE_PUMPING_STATION = "Drainage Pumping Station",
  ELECTRIC_TRANSFORMER = "Electric Transformer",
  STREET_LIGHT = "Street Light",
  TRAFFIC_SQUARE = "Traffic Square",
  BRIDGE_FLYOVER = "Bridge/Flyover",
  FARMING_LAND = "Farming Land",
  MOBILE_DRONE_PORT = "Mobile Drone Port",
  MEASUREMENT = "Measurement",
  BRIDGE = "Bridge",
  SOLAR = "Solar",
  ROAD = "Road",
  STREET = "Street",
  GARBAGE_COLLECTION_AREA = "Garbage Collection Area",
}

export const featureType = {
  // from database (single type or majority)
  [vectorProps.ZONE_BOUNDARY]: featureTypes.MULTI_POLYGON,
  [vectorProps.BLOCK_BOUNDARY]: featureTypes.MULTI_POLYGON,
  [vectorProps.AREA_BOUNDARY]: featureTypes.MULTI_POLYGON,
  [vectorProps.MEDIAN]: featureTypes.MULTI_POLYGON,
  [vectorProps.DRAINAGE_NETWORK]: featureTypes.MULTI_LINE_STRING,
  [vectorProps.ELECTRIC_POLE]: featureTypes.POINT,
  [vectorProps.GARBAGE_COLLECTION_POINT]: featureTypes.POINT,
  [vectorProps.LANDMARK]: featureTypes.POINT,
  [vectorProps.SOLAR_AREA]: featureTypes.MULTI_POLYGON,
  [vectorProps.METRO_STATION]: featureTypes.POINT,
  [vectorProps.PLAYGROUND]: featureTypes.MULTI_POLYGON,
  [vectorProps.ELECTION_WARD_BOUNDARY]: featureTypes.MULTI_LINE_STRING,
  [vectorProps.CARRIAGE_WAY]: featureTypes.MULTI_LINE_STRING,
  [vectorProps.CYCLE_TRACK]: featureTypes.MULTI_POLYGON,
  [vectorProps.CANAL]: featureTypes.MULTI_POLYGON,
  [vectorProps.POWER_SUPPLY_NETWORK]: featureTypes.MULTI_LINE_STRING,
  [vectorProps.MANHOLE]: featureTypes.POINT,
  [vectorProps.BUS_SHELTERS]: featureTypes.POINT,
  [vectorProps.METRO_ROUTE]: featureTypes.MULTI_LINE_STRING,
  [vectorProps.WATER_BODY]: featureTypes.MULTI_POLYGON,
  [vectorProps.GREEN_VERGE]: featureTypes.MULTI_POLYGON,
  [vectorProps.REVENUE_WARD_BOUNDARY]: featureTypes.MULTI_LINE_STRING,
  [vectorProps.ROUNDABOUT]: featureTypes.MULTI_POLYGON,
  [vectorProps.PLOT]: featureTypes.MULTI_POLYGON,
  [vectorProps.BOUNDARY_WALL]: featureTypes.MULTI_LINE_STRING,
  [vectorProps.PUMPING_STATION]: featureTypes.POINT,
  [vectorProps.OVER_HEAD_TANK]: featureTypes.POINT,
  [vectorProps.SEWERAGE_NETWORK]: featureTypes.MULTI_POLYGON,
  [vectorProps.PUBLIC_CONVENIENCE]: featureTypes.POINT,
  [vectorProps.BUILDING_FOOTPRINT]: featureTypes.MULTI_POLYGON,
  [vectorProps.JUNGLE]: featureTypes.MULTI_POLYGON,
  [vectorProps.PARK]: featureTypes.MULTI_POLYGON,
  [vectorProps.SECTOR_BOUNDARY]: featureTypes.MULTI_POLYGON,
  [vectorProps.RIGHT_OF_WAY]: featureTypes.MULTI_POLYGON,
  [vectorProps.FOOTPATH]: featureTypes.MULTI_POLYGON,
  [vectorProps.PARCEL]: featureTypes.MULTI_POLYGON,
  [vectorProps.CIRCLE]: featureTypes.MULTI_POLYGON,
  [vectorProps.WATER_TRANSMISSION_LINE]: featureTypes.MULTI_LINE_STRING,
  [vectorProps.WATER_TREATMENT_PLANT]: featureTypes.MULTI_POLYGON,
  [vectorProps.DRAINAGE_PUMPING_STATION]: featureTypes.POINT,
  [vectorProps.ELECTRIC_TRANSFORMER]: featureTypes.POINT,
  [vectorProps.STREET_LIGHT]: featureTypes.POINT,
  [vectorProps.TRAFFIC_SQUARE]: featureTypes.POINT,
  [vectorProps.BRIDGE_FLYOVER]: featureTypes.MULTI_POLYGON,
  [vectorProps.FARMING_LAND]: featureTypes.POINT,
  [vectorProps.MEASUREMENT]: featureTypes.MULTI_POLYGON,
  [vectorProps.BRIDGE]: featureTypes.POINT, // ambiguous
  [vectorProps.SOLAR]: featureTypes.POINT,
  [vectorProps.ROAD]: featureTypes.MULTI_LINE_STRING,
  [vectorProps.STREET]: featureTypes.MULTI_LINE_STRING,
  [vectorProps.GARBAGE_COLLECTION_AREA]: featureTypes.MULTI_POLYGON,

  // deduced
  [vectorProps.VACANT_PLOT]: featureTypes.MULTI_POLYGON,
  [vectorProps.CYCLE_STAND]: featureTypes.MULTI_POLYGON,
  [vectorProps.SUB_STATION]: featureTypes.MULTI_POLYGON,
  [vectorProps.RESTRICTED_AREA]: featureTypes.MULTI_POLYGON,
  [vectorProps.LANDFILL]: featureTypes.MULTI_POLYGON,
  [vectorProps.FLYOVER]: featureTypes.MULTI_LINE_STRING,
  [vectorProps.CELLPHONE_TOWER]: featureTypes.POINT,
  [vectorProps.PARKING_AREA]: featureTypes.MULTI_POLYGON,
  [vectorProps.POTHOLES]: featureTypes.POINT,
  [vectorProps.MUNICIPAL_BOUNDARY]: featureTypes.MULTI_LINE_STRING, // following other similar boundaries like "Election Ward Boundary" or "Revenue Ward Boundary"
  [vectorProps.PANCHAYAT_BOUNDARY]: featureTypes.MULTI_LINE_STRING, // following other similar boundaries like "Election Ward Boundary" or "Revenue Ward Boundary"
  [vectorProps.FIRE_STATION]: featureTypes.POINT, // since "drainage pumping station", "pumping station", "metro station" all are points
  [vectorProps.SLUM_BOUNDARY]: featureTypes.MULTI_POLYGON, // following other similar boundaries like "block boundary", "area boundary", "zone boundary"
  [vectorProps.MOBILE_DRONE_PORT]: featureTypes.POINT,
};
