/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An offset to apply to property values. Only applicable to `SCALAR`, `VECN`, and `MATN` types when the component type is `FLOAT32` or `FLOAT64`, or when the property is `normalized`. Not applicable to variable-length arrays.
 */
export type NumericValue = number | Numeric1DArray | Numeric2DArray;
/**
 * An array of numeric values
 *
 * @minItems 1
 */
export type Numeric1DArray = [number, ...number[]];
/**
 * An array of arrays of numeric values
 *
 * @minItems 1
 */
export type Numeric2DArray = [Numeric1DArray, ...Numeric1DArray[]];
/**
 * A scale to apply to property values. Only applicable to `SCALAR`, `VECN`, and `MATN` types when the component type is `FLOAT32` or `FLOAT64`, or when the property is `normalized`. Not applicable to variable-length arrays.
 */
export type NumericValue1 = number | Numeric1DArray | Numeric2DArray;
/**
 * Maximum allowed value for the property. Only applicable to `SCALAR`, `VECN`, and `MATN` types. This is the maximum of all property values, after the transforms based on the `normalized`, `offset`, and `scale` properties have been applied. Not applicable to variable-length arrays.
 */
export type NumericValue2 = number | Numeric1DArray | Numeric2DArray;
/**
 * Minimum allowed value for the property. Only applicable to `SCALAR`, `VECN`, and `MATN` types. This is the minimum of all property values, after the transforms based on the `normalized`, `offset`, and `scale` properties have been applied. Not applicable to variable-length arrays.
 */
export type NumericValue3 = number | Numeric1DArray | Numeric2DArray;
/**
 * A `noData` value represents missing data — also known as a sentinel value — wherever it appears. `BOOLEAN` properties may not specify `noData` values. This is given as the plain property value, without the transforms from the `normalized`, `offset`, and `scale` properties. Shall not be defined if `required` is true.
 */
export type NoDataValue = NumericValue4 | string | String1DArray;
/**
 * For `SCALAR` this is a number. For `VECN` this is an array of `N` numbers. For `MATN` this is an array of `N²` numbers. For fixed-length arrays this is an array of `count` elements of the given `type`.
 */
export type NumericValue4 = number | Numeric1DArray | Numeric2DArray;
/**
 * An array of string values
 *
 * @minItems 1
 */
export type String1DArray = [string, ...string[]];
/**
 * A default value to use when encountering a `noData` value or an omitted property. The value is given in its final form, taking the effect of `normalized`, `offset`, and `scale` properties into account. Shall not be defined if `required` is true.
 */
export type AnyValue = NumericValue4 | string | String1DArray | boolean | Boolean1DArray;
/**
 * An array of boolean values
 *
 * @minItems 1
 */
export type Boolean1DArray = [boolean, ...boolean[]];
/**
 * For `SCALAR` this is a number. For `VECN` this is an array of `N` numbers. For `MATN` this is an array of `N²` numbers. For fixed-length arrays this is an array of `count` elements of the given `type`.
 */
export type NumericValue5 = number | Numeric1DArray | Numeric2DArray;
/**
 * For `SCALAR` this is a number. For `VECN` this is an array of `N` numbers. For `MATN` this is an array of `N²` numbers. For fixed-length arrays this is an array of `count` elements of the given `type`.
 */
export type NumericValue6 = number | Numeric1DArray | Numeric2DArray;
/**
 * For `SCALAR` this is a number. For `VECN` this is an array of `N` numbers. For `MATN` this is an array of `N²` numbers. For fixed-length arrays this is an array of `count` elements of the given `type`.
 */
export type NumericValue7 = number | Numeric1DArray | Numeric2DArray;
/**
 * For `SCALAR` this is a number. For `VECN` this is an array of `N` numbers. For `MATN` this is an array of `N²` numbers. For fixed-length arrays this is an array of `count` elements of the given `type`.
 */
export type NumericValue8 = number | Numeric1DArray | Numeric2DArray;
/**
 * For `SCALAR` this is a number. For `VECN` this is an array of `N` numbers. For `MATN` this is an array of `N²` numbers. For fixed-length arrays this is an array of `count` elements of the given `type`.
 */
export type NumericValue9 = number | Numeric1DArray | Numeric2DArray;
/**
 * For `SCALAR` this is a number. For `VECN` this is an array of `N` numbers. For `MATN` this is an array of `N²` numbers. For fixed-length arrays this is an array of `count` elements of the given `type`.
 */
export type NumericValue10 = number | Numeric1DArray | Numeric2DArray;
/**
 * For `SCALAR` this is a number. For `VECN` this is an array of `N` numbers. For `MATN` this is an array of `N²` numbers. For fixed-length arrays this is an array of `count` elements of the given `type`.
 */
export type NumericValue11 = number | Numeric1DArray | Numeric2DArray;
/**
 * For `SCALAR` this is a number. For `STRING` this is a string. For `ENUM` this is a string that shall be a valid enum `name`, not an integer value. For `BOOLEAN` this is a boolean. For `VECN` this is an array of `N` numbers. For `MATN` this is an array of `N²` numbers. For fixed-length array this is an array of `count` elements of the given `type`. For variable-length arrays this is an array of any length of the given `type`.
 */
export type AnyValue1 = NumericValue4 | string | String1DArray | boolean | Boolean1DArray;
/**
 * A template URI pointing to subtree files. A subtree is a fixed-depth (defined by `subtreeLevels`) portion of the tree to keep memory use bounded. The URI of each file is substituted with the subtree root's global level, x, and y. For subdivision scheme `OCTREE`, z shall also be given. Relative paths are relative to the tileset JSON.
 */
export type TemplateURI = string;

/**
 * A 3D Tiles tileset.
 */
export interface Tileset {
  asset: Asset;
  /**
   * @deprecated
   * A dictionary object of metadata about per-feature properties.
   */
  properties?: {
    [k: string]: Properties;
  };
  schema?: Schema;
  /**
   * The URI (or IRI) of the external schema file. When this is defined, then `schema` shall be undefined.
   */
  schemaUri?: string;
  statistics?: Statistics;
  /**
   * An array of groups that tile content may belong to. Each element of this array is a metadata entity that describes the group. The tile content `group` property is an index into this array.
   *
   * @minItems 1
   */
  groups?: [GroupMetadata, ...GroupMetadata[]];
  metadata?: MetadataEntity;
  /**
   * The error, in meters, introduced if this tileset is not rendered. At runtime, the geometric error is used to compute screen space error (SSE), i.e., the error measured in pixels.
   */
  geometricError: number;
  root: Tile;
  /**
   * Names of 3D Tiles extensions used somewhere in this tileset.
   *
   * @minItems 1
   */
  extensionsUsed?: [string, ...string[]];
  /**
   * Names of 3D Tiles extensions required to properly load this tileset. Each element of this array shall also be contained in `extensionsUsed`.
   *
   * @minItems 1
   */
  extensionsRequired?: [string, ...string[]];
  [k: string]: unknown;
}
/**
 * Metadata about the entire tileset.
 */
export interface Asset {
  /**
   * The 3D Tiles version. The version defines the JSON schema for the tileset JSON and the base set of tile formats.
   */
  version: string;
  /**
   * Application-specific version of this tileset, e.g., for when an existing tileset is updated.
   */
  tilesetVersion?: string;
  [k: string]: unknown;
}
/**
 * A dictionary object of metadata about per-feature properties.
 */
export interface Properties {
  /**
   * The maximum value of this property of all the features in the tileset. The maximum value shall not be smaller than the minimum value.
   */
  maximum: number;
  /**
   * The minimum value of this property of all the features in the tileset. The maximum value shall not be smaller than the minimum value.
   */
  minimum: number;
  [k: string]: unknown;
}
/**
 * An object defining the structure of metadata classes and enums. When this is defined, then `schemaUri` shall be undefined.
 */
export interface Schema {
  /**
   * Unique identifier for the schema. Schema IDs shall be alphanumeric identifiers matching the regular expression `^[a-zA-Z_][a-zA-Z0-9_]*$`.
   */
  id: string;
  /**
   * The name of the schema, e.g. for display purposes.
   */
  name?: string;
  /**
   * The description of the schema.
   */
  description?: string;
  /**
   * Application-specific version of the schema.
   */
  version?: string;
  /**
   * A dictionary, where each key is a class ID and each value is an object defining the class. Class IDs shall be alphanumeric identifiers matching the regular expression `^[a-zA-Z_][a-zA-Z0-9_]*$`.
   */
  classes?: {
    [k: string]: Class;
  };
  /**
   * A dictionary, where each key is an enum ID and each value is an object defining the values for the enum. Enum IDs shall be alphanumeric identifiers matching the regular expression `^[a-zA-Z_][a-zA-Z0-9_]*$`.
   */
  enums?: {
    [k: string]: Enum;
  };
  [k: string]: unknown;
}
/**
 * A class containing a set of properties.
 */
export interface Class {
  /**
   * The name of the class, e.g. for display purposes.
   */
  name?: string;
  /**
   * The description of the class.
   */
  description?: string;
  /**
   * A dictionary, where each key is a property ID and each value is an object defining the property. Property IDs shall be alphanumeric identifiers matching the regular expression `^[a-zA-Z_][a-zA-Z0-9_]*$`.
   */
  properties?: {
    [k: string]: ClassProperty;
  };
  [k: string]: unknown;
}
/**
 * A single property of a metadata class.
 */
export interface ClassProperty {
  /**
   * The name of the property, e.g. for display purposes.
   */
  name?: string;
  /**
   * The description of the property.
   */
  description?: string;
  /**
   * The element type.
   */
  type: "SCALAR" | "VEC2" | "VEC3" | "VEC4" | "MAT2" | "MAT3" | "MAT4" | "STRING" | "BOOLEAN" | "ENUM" | string;
  /**
   * The datatype of the element's components. Required for `SCALAR`, `VECN`, and `MATN` types, and disallowed for other types.
   */
  componentType?:
    | "INT8"
    | "UINT8"
    | "INT16"
    | "UINT16"
    | "INT32"
    | "UINT32"
    | "INT64"
    | "UINT64"
    | "FLOAT32"
    | "FLOAT64"
    | string;
  /**
   * Enum ID as declared in the `enums` dictionary. Required when `type` is `ENUM`. Disallowed when `type` is not `ENUM`
   */
  enumType?: string;
  /**
   * Whether the property is an array. When `count` is defined the property is a fixed-length array. Otherwise the property is a variable-length array.
   */
  array?: boolean;
  /**
   * The number of array elements. May only be defined when `array` is `true`.
   */
  count?: number;
  /**
   * Specifies whether integer values are normalized. Only applicable to `SCALAR`, `VECN`, and `MATN` types with integer component types. For unsigned integer component types, values are normalized between `[0.0, 1.0]`. For signed integer component types, values are normalized between `[-1.0, 1.0]`. For all other component types, this property shall be false.
   */
  normalized?: boolean;
  offset?: NumericValue;
  scale?: NumericValue1;
  max?: NumericValue2;
  min?: NumericValue3;
  /**
   * If required, the property shall be present in every entity conforming to the class. If not required, individual entities may include `noData` values, or the entire property may be omitted. As a result, `noData` has no effect on a required property. Client implementations may use required properties to make performance optimizations.
   */
  required?: boolean;
  noData?: NoDataValue;
  default?: AnyValue;
  /**
   * An identifier that describes how this property should be interpreted. The semantic cannot be used by other properties in the class.
   */
  semantic?: string;
  [k: string]: unknown;
}
/**
 * An object defining the values of an enum.
 */
export interface Enum {
  /**
   * The name of the enum, e.g. for display purposes.
   */
  name?: string;
  /**
   * The description of the enum.
   */
  description?: string;
  /**
   * The type of the integer enum value.
   */
  valueType?: "INT8" | "UINT8" | "INT16" | "UINT16" | "INT32" | "UINT32" | "INT64" | "UINT64" | string;
  /**
   * An array of enum values. Duplicate names or duplicate integer values are not allowed.
   *
   * @minItems 1
   */
  values: [EnumValue, ...EnumValue[]];
  [k: string]: unknown;
}
/**
 * An enum value.
 */
export interface EnumValue {
  /**
   * The name of the enum value.
   */
  name: string;
  /**
   * The description of the enum value.
   */
  description?: string;
  /**
   * The integer enum value.
   */
  value: number;
  [k: string]: unknown;
}
/**
 * An object containing statistics about metadata entities.
 */
export interface Statistics {
  /**
   * A dictionary, where each key corresponds to a class ID in the `classes` dictionary of the metatata schema that was defined for the tileset that contains these statistics. Each value is an object containing statistics about entities that conform to the class.
   */
  classes?: {
    [k: string]: ClassStatistics;
  };
  [k: string]: unknown;
}
/**
 * Statistics about entities that conform to a class that was defined in a metadata schema.
 */
export interface ClassStatistics {
  /**
   * The number of entities that conform to the class.
   */
  count?: number;
  /**
   * A dictionary, where each key corresponds to a property ID in the class' `properties` dictionary and each value is an object containing statistics about property values.
   */
  properties?: {
    [k: string]: PropertyStatistics;
  };
  [k: string]: unknown;
}
/**
 * Statistics about property values.
 */
export interface PropertyStatistics {
  min?: NumericValue5;
  max?: NumericValue6;
  mean?: NumericValue7;
  median?: NumericValue8;
  standardDeviation?: NumericValue9;
  variance?: NumericValue10;
  sum?: NumericValue11;
  /**
   * A dictionary, where each key corresponds to an enum `name` and each value is the number of occurrences of that enum. Only applicable when `type` is `ENUM`. For fixed-length arrays, this is an array of component-wise occurrences.
   */
  occurrences?: {
    [k: string]: number | [number, ...number[]];
  };
  [k: string]: unknown;
}
/**
 * An object containing metadata about a group.
 */
export interface GroupMetadata {
  /**
   * The class that property values conform to. The value shall be a class ID declared in the `classes` dictionary of the metadata schema.
   */
  class: string;
  /**
   * A dictionary, where each key corresponds to a property ID in the class' `properties` dictionary and each value contains the property values. The type of the value shall match the property definition: For `BOOLEAN` use `true` or `false`. For `STRING` use a JSON string. For numeric types use a JSON number. For `ENUM` use a valid enum `name`, not an integer value. For `ARRAY`, `VECN`, and `MATN` types use a JSON array containing values matching the `componentType`. Required properties shall be included in this dictionary.
   */
  properties?: {
    [k: string]: AnyValue1;
  };
  [k: string]: unknown;
}
/**
 * A metadata entity that is associated with this tileset.
 */
export interface MetadataEntity {
  /**
   * The class that property values conform to. The value shall be a class ID declared in the `classes` dictionary of the metadata schema.
   */
  class: string;
  /**
   * A dictionary, where each key corresponds to a property ID in the class' `properties` dictionary and each value contains the property values. The type of the value shall match the property definition: For `BOOLEAN` use `true` or `false`. For `STRING` use a JSON string. For numeric types use a JSON number. For `ENUM` use a valid enum `name`, not an integer value. For `ARRAY`, `VECN`, and `MATN` types use a JSON array containing values matching the `componentType`. Required properties shall be included in this dictionary.
   */
  properties?: {
    [k: string]: AnyValue1;
  };
  [k: string]: unknown;
}
/**
 * The root tile.
 */
export interface Tile {
  boundingVolume: BoundingVolume;
  viewerRequestVolume?: BoundingVolume1;
  /**
   * The error, in meters, introduced if this tile is rendered and its children are not. At runtime, the geometric error is used to compute screen space error (SSE), i.e., the error measured in pixels.
   */
  geometricError: number;
  /**
   * Specifies if additive or replacement refinement is used when traversing the tileset for rendering. This property is required for the root tile of a tileset; it is optional for all other tiles. The default is to inherit from the parent tile.
   */
  refine?: "ADD" | "REPLACE" | string;
  /**
   * A floating-point 4x4 affine transformation matrix, stored in column-major order, that transforms the tile's content--i.e., its features as well as content.boundingVolume, boundingVolume, and viewerRequestVolume--from the tile's local coordinate system to the parent tile's coordinate system, or, in the case of a root tile, from the tile's local coordinate system to the tileset's coordinate system. `transform` does not apply to any volume property when the volume is a region, defined in EPSG:4979 coordinates. `transform` scales the `geometricError` by the maximum scaling factor from the matrix.
   *
   * @minItems 16
   * @maxItems 16
   */
  transform?: [
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number
  ];
  content?: Content;
  /**
   * An array of contents. When this is defined, then `content` shall be undefined.
   *
   * @minItems 1
   */
  contents?: [Content1, ...Content1[]];
  metadata?: MetadataEntity2;
  implicitTiling?: ImplicitTiling;
  /**
   * An array of objects that define child tiles. Each child tile content is fully enclosed by its parent tile's bounding volume and, generally, has a geometricError less than its parent tile's geometricError. For leaf tiles, there are no children, and this property may not be defined.
   *
   * @minItems 1
   */
  children?: [Tile1, ...Tile1[]];
  [k: string]: unknown;
}
/**
 * The bounding volume that encloses the tile.
 */
export interface BoundingVolume {
  /**
   * An array of 12 numbers that define an oriented bounding box. The first three elements define the x, y, and z values for the center of the box. The next three elements (with indices 3, 4, and 5) define the x axis direction and half-length. The next three elements (indices 6, 7, and 8) define the y axis direction and half-length. The last three elements (indices 9, 10, and 11) define the z axis direction and half-length.
   *
   * @minItems 12
   * @maxItems 12
   */
  box?: [number, number, number, number, number, number, number, number, number, number, number, number];
  /**
   * An array of six numbers that define a bounding geographic region in EPSG:4979 coordinates with the order [west, south, east, north, minimum height, maximum height]. Longitudes and latitudes are in radians. The range for latitudes is [-PI/2,PI/2]. The range for longitudes is [-PI,PI]. The value that is given as the 'south' of the region shall not be larger than the value for the 'north' of the region. The heights are in meters above (or below) the WGS84 ellipsoid. The 'minimum height' shall not be larger than the 'maximum height'.
   *
   * @minItems 6
   * @maxItems 6
   */
  region?: [number, number, number, number, number, number];
  /**
   * An array of four numbers that define a bounding sphere. The first three elements define the x, y, and z values for the center of the sphere. The last element (with index 3) defines the radius in meters. The radius shall not be negative.
   *
   * @minItems 4
   * @maxItems 4
   */
  sphere?: [number, number, number, number];
  [k: string]: unknown;
}
/**
 * Optional bounding volume that defines the volume the viewer shall be inside of before the tile's content will be requested and before the tile will be refined based on geometricError.
 */
export interface BoundingVolume1 {
  /**
   * An array of 12 numbers that define an oriented bounding box. The first three elements define the x, y, and z values for the center of the box. The next three elements (with indices 3, 4, and 5) define the x axis direction and half-length. The next three elements (indices 6, 7, and 8) define the y axis direction and half-length. The last three elements (indices 9, 10, and 11) define the z axis direction and half-length.
   *
   * @minItems 12
   * @maxItems 12
   */
  box?: [number, number, number, number, number, number, number, number, number, number, number, number];
  /**
   * An array of six numbers that define a bounding geographic region in EPSG:4979 coordinates with the order [west, south, east, north, minimum height, maximum height]. Longitudes and latitudes are in radians. The range for latitudes is [-PI/2,PI/2]. The range for longitudes is [-PI,PI]. The value that is given as the 'south' of the region shall not be larger than the value for the 'north' of the region. The heights are in meters above (or below) the WGS84 ellipsoid. The 'minimum height' shall not be larger than the 'maximum height'.
   *
   * @minItems 6
   * @maxItems 6
   */
  region?: [number, number, number, number, number, number];
  /**
   * An array of four numbers that define a bounding sphere. The first three elements define the x, y, and z values for the center of the sphere. The last element (with index 3) defines the radius in meters. The radius shall not be negative.
   *
   * @minItems 4
   * @maxItems 4
   */
  sphere?: [number, number, number, number];
  [k: string]: unknown;
}
/**
 * Metadata about the tile's content and a link to the content. When this is omitted the tile is just used for culling. When this is defined, then `contents` shall be undefined.
 */
export interface Content {
  boundingVolume?: BoundingVolume2;
  /**
   * A uri that points to tile content. When the uri is relative, it is relative to the referring tileset JSON file.
   */
  uri: string;
  metadata?: MetadataEntity1;
  /**
   * The group this content belongs to. The value is an index into the array of `groups` that is defined for the containing tileset.
   */
  group?: number;
  [k: string]: unknown;
}
/**
 * An optional bounding volume that tightly encloses tile content. tile.boundingVolume provides spatial coherence and tile.content.boundingVolume enables tight view frustum culling. When this is omitted, tile.boundingVolume is used.
 */
export interface BoundingVolume2 {
  /**
   * An array of 12 numbers that define an oriented bounding box. The first three elements define the x, y, and z values for the center of the box. The next three elements (with indices 3, 4, and 5) define the x axis direction and half-length. The next three elements (indices 6, 7, and 8) define the y axis direction and half-length. The last three elements (indices 9, 10, and 11) define the z axis direction and half-length.
   *
   * @minItems 12
   * @maxItems 12
   */
  box?: [number, number, number, number, number, number, number, number, number, number, number, number];
  /**
   * An array of six numbers that define a bounding geographic region in EPSG:4979 coordinates with the order [west, south, east, north, minimum height, maximum height]. Longitudes and latitudes are in radians. The range for latitudes is [-PI/2,PI/2]. The range for longitudes is [-PI,PI]. The value that is given as the 'south' of the region shall not be larger than the value for the 'north' of the region. The heights are in meters above (or below) the WGS84 ellipsoid. The 'minimum height' shall not be larger than the 'maximum height'.
   *
   * @minItems 6
   * @maxItems 6
   */
  region?: [number, number, number, number, number, number];
  /**
   * An array of four numbers that define a bounding sphere. The first three elements define the x, y, and z values for the center of the sphere. The last element (with index 3) defines the radius in meters. The radius shall not be negative.
   *
   * @minItems 4
   * @maxItems 4
   */
  sphere?: [number, number, number, number];
  [k: string]: unknown;
}
/**
 * Metadata that is associated with this content.
 */
export interface MetadataEntity1 {
  /**
   * The class that property values conform to. The value shall be a class ID declared in the `classes` dictionary of the metadata schema.
   */
  class: string;
  /**
   * A dictionary, where each key corresponds to a property ID in the class' `properties` dictionary and each value contains the property values. The type of the value shall match the property definition: For `BOOLEAN` use `true` or `false`. For `STRING` use a JSON string. For numeric types use a JSON number. For `ENUM` use a valid enum `name`, not an integer value. For `ARRAY`, `VECN`, and `MATN` types use a JSON array containing values matching the `componentType`. Required properties shall be included in this dictionary.
   */
  properties?: {
    [k: string]: AnyValue1;
  };
  [k: string]: unknown;
}
/**
 * Metadata about the tile's content and a link to the content.
 */
export interface Content1 {
  boundingVolume?: BoundingVolume2;
  /**
   * A uri that points to tile content. When the uri is relative, it is relative to the referring tileset JSON file.
   */
  uri: string;
  metadata?: MetadataEntity1;
  /**
   * The group this content belongs to. The value is an index into the array of `groups` that is defined for the containing tileset.
   */
  group?: number;
  [k: string]: unknown;
}
/**
 * A metadata entity that is associated with this tile.
 */
export interface MetadataEntity2 {
  /**
   * The class that property values conform to. The value shall be a class ID declared in the `classes` dictionary of the metadata schema.
   */
  class: string;
  /**
   * A dictionary, where each key corresponds to a property ID in the class' `properties` dictionary and each value contains the property values. The type of the value shall match the property definition: For `BOOLEAN` use `true` or `false`. For `STRING` use a JSON string. For numeric types use a JSON number. For `ENUM` use a valid enum `name`, not an integer value. For `ARRAY`, `VECN`, and `MATN` types use a JSON array containing values matching the `componentType`. Required properties shall be included in this dictionary.
   */
  properties?: {
    [k: string]: AnyValue1;
  };
  [k: string]: unknown;
}
/**
 * An object that describes the implicit subdivision of this tile.
 */
export interface ImplicitTiling {
  /**
   * A string describing the subdivision scheme used within the tileset.
   */
  subdivisionScheme: "QUADTREE" | "OCTREE" | string;
  /**
   * The number of distinct levels in each subtree. For example, a quadtree with `subtreeLevels = 2` will have subtrees with 5 nodes (one root and 4 children).
   */
  subtreeLevels: number;
  /**
   * The numbers of the levels in the tree with available tiles.
   */
  availableLevels: number;
  subtrees: Subtrees;
  [k: string]: unknown;
}
/**
 * An object describing the location of subtree files.
 */
export interface Subtrees {
  uri: TemplateURI;
  [k: string]: unknown;
}
/**
 * A tile in a 3D Tiles tileset.
 */
export interface Tile1 {
  boundingVolume: BoundingVolume;
  viewerRequestVolume?: BoundingVolume1;
  /**
   * The error, in meters, introduced if this tile is rendered and its children are not. At runtime, the geometric error is used to compute screen space error (SSE), i.e., the error measured in pixels.
   */
  geometricError: number;
  /**
   * Specifies if additive or replacement refinement is used when traversing the tileset for rendering. This property is required for the root tile of a tileset; it is optional for all other tiles. The default is to inherit from the parent tile.
   */
  refine?: "ADD" | "REPLACE" | string;
  /**
   * A floating-point 4x4 affine transformation matrix, stored in column-major order, that transforms the tile's content--i.e., its features as well as content.boundingVolume, boundingVolume, and viewerRequestVolume--from the tile's local coordinate system to the parent tile's coordinate system, or, in the case of a root tile, from the tile's local coordinate system to the tileset's coordinate system. `transform` does not apply to any volume property when the volume is a region, defined in EPSG:4979 coordinates. `transform` scales the `geometricError` by the maximum scaling factor from the matrix.
   *
   * @minItems 16
   * @maxItems 16
   */
  transform?: [
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number
  ];
  content?: Content;
  /**
   * An array of contents. When this is defined, then `content` shall be undefined.
   *
   * @minItems 1
   */
  contents?: [Content1, ...Content1[]];
  metadata?: MetadataEntity2;
  implicitTiling?: ImplicitTiling;
  /**
   * An array of objects that define child tiles. Each child tile content is fully enclosed by its parent tile's bounding volume and, generally, has a geometricError less than its parent tile's geometricError. For leaf tiles, there are no children, and this property may not be defined.
   *
   * @minItems 1
   */
  children?: [Tile1, ...Tile1[]];
  [k: string]: unknown;
}
