name: Deploy to Amazon ECS

on:
  push:
    branches: [ "master-aws" ]

env:
  AWS_REGION: "ap-south-1"                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: "kesowa-server"          # set this to your Amazon ECR repository name
  ECS_SERVICE: "kesowa-server"                 # set this to your Amazon ECS service name
  ECS_CLUSTER: "kesowa-server"      # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: "./aws/task-definition.json" # set this to the path to your Amazon ECS task definition
                                               # file, e.g. .aws/task-definition.json
  CONTAINER_NAME: "kesowa-server"           # set this to the name of the container in the
                                               # containerDefinitions section of your task definition

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

      - name: Set up environment variables
        run: |
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "MONGODB_CONNECTION_STRING=${{ secrets.MONGODB_CONNECTION_STRING }}" >> .env
          echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> .env
          echo "SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}" >> .env
          echo "SMTP_SERVER=${{ secrets.SMTP_SERVER }}" >> .env
          echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> .env
          echo "MAP_KEY=${{ secrets.MAP_KEY }}" >> .env
          echo "BASE_SERVER=${{ secrets.BASE_SERVER }}" >> .env
          echo "TITILER_STATIC=${{ secrets.TITILER_STATIC }}" >> .env
          echo "FTP_PORT=${{ secrets.FTP_PORT }}" >> .env
          echo "FTP_HOST_DEV=${{ secrets.FTP_HOST_DEV }}" >> .env
          echo "FTP_HOST_PROD=${{ secrets.FTP_HOST_PROD }}" >> .env
          echo "FTP_USERNAME=${{ secrets.FTP_USERNAME }}" >> .env
          echo "FTP_PASSWORD=${{ secrets.FTP_PASSWORD }}" >> .env
          echo "RESET_PASSWORD_TOKEN_EXPIRE=${{ secrets.RESET_PASSWORD_TOKEN_EXPIRE }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "LIVE_URL=${{ secrets.LIVE_URL }}" >> .env
          echo "RAZORPAY_KEY_ID=${{ secrets.RAZORPAY_KEY_ID }}" >> .env
          echo "RAZORPAY_KEY_SECRET=${{ secrets.RAZORPAY_KEY_SECRET }}" >> .env
          echo "RAZORPAY_HOOK_SECRET=${{ secrets.RAZORPAY_HOOK_SECRET }}" >> .env
          echo "TITILER_SERVER=${{ secrets.TITILER_SERVER }}" >> .env
          echo "MODE=${{ secrets.MODE }}" >> .env
          echo "TITILER_PUBLIC=${{ secrets.TITILER_PUBLIC }}" >> .env
          echo "RTMP_PUBLIC=${{ secrets.RTMP_PUBLIC }}" >> .env
          echo "REDIS_URI=${{ secrets.REDIS_URI }}" >> .env
          echo "API_SERVER=${{ secrets.API_SERVER }}" >> .env
          echo "PUBLIC_SERVER=${{ secrets.PUBLIC_SERVER }}" >> .env
          echo "CDN_URL=${{ secrets.CDN_URL }}" >> .env
          echo "PUBLIC_DIR=${{ secrets.PUBLIC_DIR }}" >> .env
          echo "SEQ_URL=${{ secrets.SEQ_URL }}" >> .env
          echo "SEQ_KEY=${{ secrets.SEQ_KEY }}" >> .env
          echo "S3_KEY_ID=${{ secrets.S3_KEY_ID }}" >> .env
          echo "S3_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY }}" >> .env
          echo "ACCESS_KEY=${{ secrets.ACCESS_KEY }}" >> .env
          echo "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}" >> .env
          echo "AWS_S3_ENDPOINT=${{ secrets.AWS_S3_ENDPOINT }}" >> .env
          echo "AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }}" >> .env
          echo "AWS_MEDIACONVERT_ENDPOINT=${{ secrets.AWS_MEDIACONVERT_ENDPOINT }}" >> .env
          echo "ENDPOINT=${{ secrets.ENDPOINT }}" >> .env

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: "latest"
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY" >> $GITHUB_OUTPUT
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT    
    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION }}
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true