# name: Lint

# on:
#   # Trigger the workflow on push or pull request,
#   # but only for the main branch
#   push:
#     branches: ["master", "dev", "dev-aws", "master-aws"]       
#   # Replace pull_request with pull_request_target if you
#   # plan to use this action with forks, see the Limitations section
#   pull_request:
#     branches: ["master", "dev", "dev-aws", "master-aws"]

# # Down scope as necessary via https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
# permissions:
#   checks: write
#   contents: write

# jobs:
#   run-linters:
#     name: Run linters
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out Git repository
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: 16
#           cache: 'npm'

#       - name: Install Node.js dependencies
#         run: npm ci

#       # Install your linters here

#       - name: Run linters
#         uses: wearerequired/lint-action@v2
#         with:
#           # Enable your linters here
#           auto_fix: true
#           eslint: true
#           prettier: true
#           eslint_extensions: js,ts          
